services:
  nginx:
    container_name: nginx
    image: private-registry.nginx.com/nginx-plus/agent:debian
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    ports:
      - "80:80"  # Open WebUI
      - "8081:8081"  # NGINX Plus dashboard
    restart: always
    environment:
      NMS_TLS_ENABLE: true
      NMS_SERVER_GRPCPORT: 443
      NMS_SERVER_TOKEN: $NGINX_ONE_DATA_PLANE_KEY
      NGINX_AGENT_INSTANCE_GROUP: $NGINX_ONE_CONFIG_SYNC_GROUP

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    environment:
      OLLAMA_BASE_URL: http://nginx:11435
      WEBUI_AUTH: false
    volumes:
      - ./open-webui:/app/backend/data
    restart: always
